name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Solo se activa cuando hay un push a la rama 'main'

jobs:
  build_and_deploy_job:
    # Solo ejecuta el despliegue si hay un 'push' a la rama 'main'
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_MUD_0A81B3D0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Para integraciones de GitHub (por ejemplo, comentarios de PR)
          action: "upload"
          ###### Repository/Build Configurations - Estos valores se pueden configurar según los requisitos de tu app. ######
          app_location: "/"  # Ruta del código fuente de la aplicación
          api_location: "."  # Ruta del código fuente de la API (opcional)
          output_location: "."  # Directorio de contenido de la app construida (opcional)
          ###### Fin de las configuraciones ######
